# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
import re
sys.path.insert(0, os.path.abspath('..\\.'))


# -- Project information -----------------------------------------------------

project = 'Python for Transportation'
copyright = '2020 Florida Department of Transportation'
html_show_copyright = False
author = 'Cambridge Systematics, Inc. for Florida Department of Transportation'

VERSION = "1.1.2"

# The short X.Y version
version = VERSION
# The full version, including alpha/beta/rc tags
release = '{}, June 2022'.format(VERSION)


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.autosummary',
    'sphinx.ext.napoleon',
    'sphinxcontrib.restbuilder',
    'nbsphinx',
    'IPython.sphinxext.ipython_console_highlighting',
    'sphinx_rtd_theme',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of course-content filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', ]

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to course-content directory, that match files and
# directories to ignore when looking for course-content files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '**ipynb_checkpoints', '**junk']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

intersphinx_mapping = {
	'python': ('https://docs.python.org/3.7/', None),
	'numpy': ('https://docs.scipy.org/doc/numpy/', None),
	'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
	'scipy': ('https://docs.scipy.org/doc/scipy/reference/', None),
	'sklearn': ('https://scikit-learn.org/stable/', None),
    'ema_workbench': ('https://emaworkbench.readthedocs.io/en/latest/', None),
	'conda': ('https://docs.conda.io/projects/conda/en/latest/', None),
}


rst_prolog = """

.. meta::
   :robots: noindex, nofollow

"""


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_extra_path = [ 'extra' ]

html_sidebars = {
    '**': ['logo-text.html', 'globaltoc.html', 'searchbox.html']
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = "_static/logo.png"

# html_style = 'css/site.css'
